# Generated by Django 5.2.5 on 2025-09-13 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='hour',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
