# Generated by Django 5.2.5 on 2025-09-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_reservation_hour_reservation_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start',
            field=models.TimeField(),
        ),
    ]
