# Generated by Django 5.2.5 on 2025-09-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='closing_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='opening_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='tablesaloon',
            name='name',
            field=models.CharField(default='Salle par défaut', max_length=255),
            preserve_default=False,
        ),
    ]
