# Generated by Django 5.2.5 on 2025-09-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_menu_options_menu_country_menu_img_menu_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesaloon',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
